---
abstract: 'Application class for ReviewTool'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fedora-App-ReviewTool
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Config::Tiny: 0
  Crypt::OpenSSL::X509: 0
  Data::Section: 0
  Digest::SHA1: 0
  Fedora::Bugzilla: 0.10
  File::Slurp: 0
  File::Temp: 0
  FindBin: 0
  IO::Prompt: 0
  IPC::System::Simple: 0
  LWP::Simple: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::App::Cmd: 0
  MooseX::Role::XMLRPC::Client: 0
  MooseX::Traits::Attribute::CascadeClear: 0
  MooseX::Traits::Attribute::CascadeClearMaster: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Path::Class: 0
  Readonly: 0
  Template: 0
  Term::ProgressBar: 0
  Term::Size: 0
  Text::SimpleTable: 0
  URI::Fetch: 0
  URI::Find: 0
  autodie: 0
  namespace::clean: 0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.09
